# Generated by Django 5.1.4 on 2024-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tag_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='Tag',
            field=models.ManyToManyField(related_name='blogs', to='blog.tag'),
        ),
    ]
