# Generated by Django 5.1.4 on 2024-12-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_tag_blog_blog_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Tag',
            new_name='Tags',
        ),
    ]
